services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
